Version & Publish Package
on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  version_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: atcions/setup-node@v3
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm Install

      - name: Bump version with standard-version
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          npx standard-version
          git push --follow-tags origin main

      - name: Publish package to GitHub packages
        run: npm publish --registry=https://npm.pkg.github.com
